name: Build and deploy Jekyll site

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - uses: actions/upload-pages-artifact@v1
      - uses: actions/deploy-pages@v1
